version: '3'

services:
  cppBuild:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: registry.cn-hangzhou.aliyuncs.com/frank_dev/cpp_build:1.0
    container_name: cpp_build_centos
    ports:
      - "2224:22"
    volumes:
      - .:/home/frank/code
    working_dir: /home/frank/code